### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by iahmad-khan** [magicmark/composerize#53]
```
[iahmad@web-prod-ijaz001 ~]$ composerize docker run --name nginx --image nginx
/usr/lib/node_modules/composerize/dist/composerize.js:1
(function (exports, require, module, __filename, __dirname) { !function(t,e){"object"==typeof exports&&"undefined"!=typeof module?module.exports=e():"function"==typeof define&&define.amd?define(e):t.composerize=e()}(this,function(){"use strict";function t(){throw new Error("Dynamic requires are not currently supported by rollup-plugin-commonjs")}function e(){throw new Error("setTimeout has not been defined")}function n(){throw new Error("clearTimeout has not been defined")}function r(t){if(hn===setTimeout)return setTimeout(t,0);if((hn===e||!hn)&&setTimeout)return hn=setTimeout,setTimeout(t,0);try{return hn(t,0)}catch(e){try{return hn.call(null,t,0)}catch(e){return hn.call(this,t,0)}}}function i(t){if(pn===clearTimeout)return clearTimeout(t);if((pn===n||!pn)&&clearTimeout)return pn=clearTimeout,clearTimeout(t);try{return pn(t)}catch(e){try{return pn.call(null,t)}catch(e){return pn.call(this,t)}}}function o(){dn&&gn&&(dn=!1,gn.length?yn=gn.concat(yn):En=

TypeError: Object.entries is not a function
    at /usr/lib/node_modules/composerize/dist/composerize.js:1:74055
    at Object.<anonymous> (/usr/lib/node_modules/composerize/cli.js:6:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

```

**Comment by magicmark** [comment]
What version are you using? Seems to work for me with the latest version (1.0.4):

```
╔═ markl@C02VC2CUHTD8: /var/folders/xp/n5tbdrrs761ck82qqychcf61ptmq9d/T/tmp.F65sufDvcX
╚═ ♪ yarn info composerize version
yarn info v1.17.3
1.0.4
✨  Done in 0.12s.

╔═ markl@C02VC2CUHTD8: /var/folders/xp/n5tbdrrs761ck82qqychcf61ptmq9d/T/tmp.F65sufDvcX
╚═ ♪ yarn composerize docker run --name nginx --image nginx
yarn run v1.17.3
$ /private/var/folders/xp/n5tbdrrs761ck82qqychcf61ptmq9d/T/tmp.F65sufDvcX/node_modules/.bin/composerize docker run --name nginx --image nginx
version: '3.3'
services:
    run:
        container_name: nginx
        image: run
✨  Done in 0.15s.
```
